version: "2"

run:
  timeout: 5m

linters:
  default: standard

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/sadiksaifi/voice
    golines:
      max-len: 80
      tab-len: 4
